// Fluent Emoji 3D asset URLs via jsDelivr CDN (microsoft/fluentui-emoji@main)
// Human/skin-sensitive emojis use "Dark" tone per project settings.

const BASE = "https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji@main/assets";

function std(folder: string, file: string) {
  return `${BASE}/${folder}/3D/${file}_3d.png`;
}
function skin(folder: string, file: string, tone = "Dark") {
  return `${BASE}/${folder}/${tone}/3D/${file}_${tone.toLowerCase()}_3d.png`;
}

// Map from emoji character → Fluent 3D PNG URL.
// ZWJ sequences and number keycaps are intentionally omitted (no Fluent 3D equivalent).
export const FLUENT_MAP: Record<string, string> = {
  // ── Animals ──────────────────────────────────────────────────────────────
  "🦁": std("Lion",               "lion"),
  "🐘": std("Elephant",           "elephant"),
  "🦒": std("Giraffe",            "giraffe"),
  "🐕": std("Dog",                "dog"),
  "🐱": std("Cat Face",           "cat_face"),
  "🐦": std("Bird",               "bird"),
  "🐐": std("Goat",               "goat"),
  "🐄": std("Cow",                "cow"),
  "🫏": std("Donkey",             "donkey"),
  "🐎": std("Horse",              "horse"),
  "🐑": std("Ewe",                "ewe"),
  "🐔": std("Chicken",            "chicken"),
  "🦆": std("Duck",               "duck"),
  "🦜": std("Parrot",             "parrot"),
  "🐒": std("Monkey",             "monkey"),
  "🐆": std("Leopard",            "leopard"),
  "🐺": std("Wolf",               "wolf"),
  "🦛": std("Hippopotamus",       "hippopotamus"),
  "🐇": std("Rabbit",             "rabbit"),
  "🐭": std("Mouse Face",         "mouse_face"),
  "🦏": std("Rhinoceros",         "rhinoceros"),
  "🦓": std("Zebra",              "zebra"),
  "🐃": std("Water Buffalo",      "water_buffalo"),
  "🦅": std("Eagle",              "eagle"),
  "🐍": std("Snake",              "snake"),
  "🐟": std("Fish",               "fish"),
  "🐝": std("Honeybee",          "honeybee"),
  "🦋": std("Butterfly",         "butterfly"),
  "🦟": std("Mosquito",          "mosquito"),
  "🐷": std("Pig Face",          "pig_face"),
  "🦈": std("Shark",             "shark"),
  "🐋": std("Spouting Whale",    "spouting_whale"),
  "🐢": std("Turtle",            "turtle"),
  "🐗": std("Boar",              "boar"),
  "🐙": std("Octopus",           "octopus"),
  "🦌": std("Deer",              "deer"),
  "🦢": std("Swan",              "swan"),
  "🦂": std("Scorpion",          "scorpion"),

  // ── Colors ───────────────────────────────────────────────────────────────
  "🔴": std("Red Circle",         "red_circle"),
  "🔵": std("Blue Circle",        "blue_circle"),
  "🟡": std("Yellow Circle",      "yellow_circle"),
  "🟢": std("Green Circle",       "green_circle"),
  "⚪": std("White Circle",       "white_circle"),
  "⚫": std("Black Circle",       "black_circle"),
  "🩷": std("Pink Heart",         "pink_heart"),
  "🟣": std("Purple Circle",      "purple_circle"),
  "🟤": std("Brown Circle",       "brown_circle"),
  "🩶": std("Grey Heart",         "grey_heart"),

  // ── Body parts ───────────────────────────────────────────────────────────
  "🧠": std("Brain",              "brain"),
  "👁️": std("Eye",               "eye"),
  "👂": skin("Ear",               "ear"),
  "👃": skin("Nose",              "nose"),
  "👄": std("Mouth",              "mouth"),
  "🤚": skin("Raised Back of Hand","raised_back_of_hand"),
  "👆": skin("Backhand Index Pointing Up","backhand_index_pointing_up"),
  "🦵": skin("Leg",               "leg"),
  "🦷": std("Tooth",              "tooth"),
  "💪": skin("Flexed Biceps",     "flexed_biceps"),
  "🫀": std("Anatomical Heart",   "anatomical_heart"),
  "❤️": std("Red Heart",          "red_heart"),
  "🩸": std("Drop of Blood",      "drop_of_blood"),
  "🫴": skin("Palm Up Hand",      "palm_up_hand"),
  "🧍": skin("Person Standing",   "person_standing"),
  "💇": skin("Person Getting Haircut","person_getting_haircut"),
  "👅": std("Tongue",                "tongue"),
  "🦴": std("Bone",                  "bone"),
  "🫁": std("Lungs",                 "lungs"),
  "🩱": std("One-Piece Swimsuit",    "one-piece_swimsuit"),
  "💦": std("Sweat Droplets",        "sweat_droplets"),
  "🖐️": skin("Hand with Fingers Splayed","hand_with_fingers_splayed"),
  "😬": std("Grimacing Face",        "grimacing_face"),
  "🤦": skin("Person Facepalming",   "person_facepalming"),
  "🦶": skin("Foot",                 "foot"),
  "👍": skin("Thumbs Up",            "thumbs_up"),

  // ── People (all Dark skin tone) ──────────────────────────────────────────
  "👩": skin("Woman",             "woman"),
  "👨": skin("Man",               "man"),
  "👦": skin("Boy",               "boy"),
  "👧": skin("Girl",              "girl"),
  "👵": skin("Old Woman",         "old_woman"),
  "👴": skin("Old Man",           "old_man"),
  "👶": skin("Baby",              "baby"),
  "🤝": std("Handshake",          "handshake"),
  "👮": skin("Police Officer",    "police_officer"),
  "🎓": std("Graduation Cap",     "graduation_cap"),
  "🏘️": std("Houses",            "houses"),
  "🚗": std("Automobile",         "automobile"),

  // ── Food / Chakula ───────────────────────────────────────────────────────
  "💧": std("Droplet",            "droplet"),
  "🍽️": std("Fork and Knife with Plate","fork_and_knife_with_plate"),
  "🍞": std("Bread",              "bread"),
  "🍎": std("Red Apple",          "red_apple"),
  "🥩": std("Cut of Meat",        "cut_of_meat"),
  "🍚": std("Cooked Rice",        "cooked_rice"),
  "🫕": std("Fondue",             "fondue"),
  "🍌": std("Banana",             "banana"),
  "🥭": std("Mango",              "mango"),
  "🥦": std("Broccoli",           "broccoli"),
  "🫖": std("Teapot",             "teapot"),
  "🥛": std("Glass of Milk",      "glass_of_milk"),
  "🥚": std("Egg",                "egg"),
  "🌽": std("Ear of Corn",        "ear_of_corn"),
  "🍅": std("Tomato",             "tomato"),
  "🫘": std("Beans",              "beans"),
  "🍬": std("Candy",              "candy"),
  "🍯": std("Honey Pot",          "honey_pot"),
  "🥣": std("Bowl with Spoon",    "bowl_with_spoon"),
  "🧅": std("Onion",             "onion"),
  "🥔": std("Potato",            "potato"),
  "🧂": std("Salt",              "salt"),
  "🍛": std("Curry Rice",        "curry_rice"),
  "🎂": std("Birthday Cake",     "birthday_cake"),
  "🍪": std("Cookie",            "cookie"),
  "🥥": std("Coconut",           "coconut"),
  "🍈": std("Melon",             "melon"),
  "🍉": std("Watermelon",        "watermelon"),
  "🍇": std("Grapes",            "grapes"),
  "🥕": std("Carrot",            "carrot"),
  "🥬": std("Leafy Green",       "leafy_green"),
  "🍟": std("French Fries",      "french_fries"),
  "🍲": std("Pot of Food",       "pot_of_food"),
  "🥐": std("Croissant",         "croissant"),
  "🧃": std("Beverage Box",      "beverage_box"),
  "🫙": std("Jar",               "jar"),

  // ── Action Verbs / Vitenzi ───────────────────────────────────────────────
  "🥤": std("Cup with Straw",     "cup_with_straw"),
  "😴": std("Sleeping Face",      "sleeping_face"),
  "⚽": std("Soccer Ball",        "soccer_ball"),
  "🏃": skin("Person Running",    "person_running"),
  "🦘": std("Kangaroo",           "kangaroo"),
  "📖": std("Open Book",          "open_book"),
  "🎵": std("Musical Note",       "musical_note"),
  "🍳": std("Cooking",            "cooking"),
  "🚶": skin("Person Walking",    "person_walking"),
  "🫳": skin("Palm Down Hand",    "palm_down_hand"),
  "👋": skin("Waving Hand",       "waving_hand"),
  "👀": std("Eyes",               "eyes"),
  "🗣️": std("Speaking Head",     "speaking_head"),
  "✍️": skin("Writing Hand",      "writing_hand"),
  "😂": std("Face with Tears of Joy","face_with_tears_of_joy"),
  "🧼": std("Soap",               "soap"),
  "🛠️": std("Hammer and Wrench", "hammer_and_wrench"),
  "🚪": std("Door",               "door"),
  "🔒": std("Locked",             "locked"),
  "📦": std("Package",            "package"),
  "🔄": std("Counterclockwise Arrows Button","counterclockwise_arrows_button"),
  "🏠": std("House",              "house"),
  "🧗": skin("Person Climbing",   "person_climbing"),
  "👕": std("T-Shirt",            "t-shirt"),
  "👊": skin("Oncoming Fist",     "oncoming_fist"),

  // ── People extras ────────────────────────────────────────────────────────
  "⛪": std("Church",             "church"),

  // ── School / Shule ───────────────────────────────────────────────────────
  "🏫": std("School",             "school"),
  "🖊️": std("Pen",               "pen"),
  "🎒": std("Backpack",           "backpack"),
  "✏️": std("Pencil",            "pencil"),
  "🪑": std("Chair",              "chair"),
  "📝": std("Memo",               "memo"),
  "🔢": std("Input Numbers",      "input_numbers"),
  "🔬": std("Microscope",         "microscope"),
  "🎨": std("Artist Palette",     "artist_palette"),
  "🏆": std("Trophy",             "trophy"),
  "📜": std("Scroll",            "scroll"),
  "🗺️": std("World Map",        "world_map"),
  "📏": std("Straight Ruler",    "straight_ruler"),
  "🖍️": std("Crayon",           "crayon"),
  "📅": std("Calendar",          "calendar"),
  "🪟": std("Window",            "window"),
  "📷": std("Camera",            "camera"),

  // ── Feelings / Hisia ─────────────────────────────────────────────────────
  "😊": std("Smiling Face with Smiling Eyes","smiling_face_with_smiling_eyes"),
  "😢": std("Crying Face",        "crying_face"),
  "😠": std("Angry Face",         "angry_face"),
  "😨": std("Fearful Face",       "fearful_face"),
  "🎉": std("Party Popper",       "party_popper"),
  "😳": std("Flushed Face",       "flushed_face"),
  "😤": std("Face with Steam from Nose","face_with_steam_from_nose"),
  "😟": std("Worried Face",       "worried_face"),
  "😲": std("Astonished Face",    "astonished_face"),
  "🥺": std("Pleading Face",      "pleading_face"),
  "🙏": skin("Folded Hands",      "folded_hands"),
  "🌟": std("Glowing Star",       "glowing_star"),
  "🕊️": std("Dove",              "dove"),
  "⏳": std("Hourglass Not Done", "hourglass_not_done"),
  "😌": std("Relieved Face",      "relieved_face"),
  "😒": std("Unamused Face",      "unamused_face"),
  "💕": std("Two Hearts",         "two_hearts"),
  "💭": std("Thought Balloon",    "thought_balloon"),
  "🎭": std("Performing Arts",    "performing_arts"),
  "💫": std("Dizzy",              "dizzy"),
  "🌠": std("Shooting Star",      "shooting_star"),

  // ── Nature / Mazingira ───────────────────────────────────────────────────
  "🌳": std("Deciduous Tree",     "deciduous_tree"),
  "☀️": std("Sun",               "sun"),
  "🌧️": std("Cloud with Rain",   "cloud_with_rain"),
  "🌍": std("Globe Showing Europe-Africa","globe_showing_europe-africa"),
  "🌸": std("Cherry Blossom",     "cherry_blossom"),
  "🏞️": std("National Park",     "national_park"),
  "⛰️": std("Mountain",          "mountain"),
  "🌊": std("Water Wave",         "water_wave"),
  "🌾": std("Sheaf of Rice",      "sheaf_of_rice"),
  "🌲": std("Evergreen Tree",     "evergreen_tree"),
  "💨": std("Dashing Away",       "dashing_away"),
  "🥶": std("Cold Face",          "cold_face"),
  "🔥": std("Fire",               "fire"),
  "🌤️": std("Sun Behind Small Cloud","sun_behind_small_cloud"),
  "⭐": std("Star",               "star"),
  "🌙": std("Crescent Moon",      "crescent_moon"),
  "☁️": std("Cloud",             "cloud"),
  "🏖️": std("Beach with Umbrella","beach_with_umbrella"),
  "🪨": std("Rock",               "rock"),
  "⛈️": std("Cloud with Lightning and Rain","cloud_with_lightning_and_rain"),
  "⚡": std("High Voltage",       "high_voltage"),
  "💡": std("Light Bulb",         "light_bulb"),
  "🌑": std("New Moon",           "new_moon"),
  "🏝️": std("Desert Island",     "desert_island"),
  "🏜️": std("Desert",            "desert"),
  "🧊": std("Ice",                "ice"),

  // ── Ordinals / Numbers ───────────────────────────────────────────────────
  "🥇": std("1st Place Medal",    "1st_place_medal"),
  "🥈": std("2nd Place Medal",    "2nd_place_medal"),
  "🥉": std("3rd Place Medal",    "3rd_place_medal"),
  "🌗": std("Last Quarter Moon",  "last_quarter_moon"),
  "🌘": std("Waning Crescent Moon","waning_crescent_moon"),
  "💰": std("Money Bag",          "money_bag"),
};

export function getFluentUrl(emoji: string): string | null {
  return FLUENT_MAP[emoji] ?? null;
}

// ── Animated PNG URLs — Tarikul-Islam-Anik/Animated-Fluent-Emojis via jsDelivr ─
// Official Microsoft Fluent animated emoji set (APNG). Renders with a plain <img>.
// Any emoji not in this map falls back to the static Fluent 3D PNG in FLUENT_MAP.

const ANIM_BASE = "https://cdn.jsdelivr.net/gh/Tarikul-Islam-Anik/Animated-Fluent-Emojis@master/Emojis";

function af(category: string, name: string): string {
  return `${ANIM_BASE}/${encodeURIComponent(category)}/${encodeURIComponent(name)}.png`;
}

export const ANIMATED_MAP: Record<string, string> = {
  // ── Animals ───────────────────────────────────────────────────────────────
  "🦁": af("Animals", "Lion"),
  "🐘": af("Animals", "Elephant"),
  "🦒": af("Animals", "Giraffe"),
  "🐕": af("Animals", "Dog"),
  "🐱": af("Animals", "Cat Face"),
  "🐦": af("Animals", "Bird"),
  "🐐": af("Animals", "Goat"),
  "🐄": af("Animals", "Cow"),
  "🫏": af("Animals", "Donkey"),
  "🐎": af("Animals", "Horse"),
  "🐑": af("Animals", "Ewe"),
  "🐔": af("Animals", "Chicken"),
  "🦆": af("Animals", "Duck"),
  "🦜": af("Animals", "Parrot"),
  "🐒": af("Animals", "Monkey"),
  "🐆": af("Animals", "Leopard"),
  "🐺": af("Animals", "Wolf"),
  "🦛": af("Animals", "Hippopotamus"),
  "🐇": af("Animals", "Rabbit"),
  "🐭": af("Animals", "Mouse Face"),
  "🦏": af("Animals", "Rhinoceros"),
  "🦓": af("Animals", "Zebra"),
  "🐃": af("Animals", "Water Buffalo"),
  "🦅": af("Animals", "Eagle"),
  "🐍": af("Animals", "Snake"),
  "🐟": af("Animals", "Fish"),
  "🐝": af("Animals", "Honeybee"),
  "🦋": af("Animals", "Butterfly"),
  "🦟": af("Animals", "Mosquito"),
  "🐷": af("Animals", "Pig Face"),
  "🦈": af("Animals", "Shark"),
  "🐢": af("Animals", "Turtle"),
  "🐗": af("Animals", "Boar"),
  "🐙": af("Animals", "Octopus"),
  "🦌": af("Animals", "Deer"),
  "🦢": af("Animals", "Swan"),
  "🦂": af("Animals", "Scorpion"),

  // ── Food / Chakula ────────────────────────────────────────────────────────
  "🍽️": af("Food", "Fork and Knife with Plate"),
  "🍞": af("Food", "Bread"),
  "🍎": af("Food", "Red Apple"),
  "🥩": af("Food", "Cut of Meat"),
  "🍚": af("Food", "Cooked Rice"),
  "🫕": af("Food", "Fondue"),
  "🍌": af("Food", "Banana"),
  "🥭": af("Food", "Mango"),
  "🥦": af("Food", "Broccoli"),
  "🫖": af("Food", "Teapot"),
  "🥛": af("Food", "Glass of Milk"),
  "🥚": af("Food", "Egg"),
  "🌽": af("Food", "Ear of Corn"),
  "🍅": af("Food", "Tomato"),
  "🫘": af("Food", "Beans"),
  "🍬": af("Food", "Candy"),
  "🍯": af("Food", "Honey Pot"),
  "🥣": af("Food", "Bowl with Spoon"),
  "🥤": af("Food", "Cup with Straw"),
  "🍳": af("Food", "Cooking"),
  "🧅": af("Food", "Onion"),
  "🥔": af("Food", "Potato"),
  "🍉": af("Food", "Watermelon"),
  "🍇": af("Food", "Grapes"),
  "🥕": af("Food", "Carrot"),
  "🥬": af("Food", "Leafy Green"),
  "🍟": af("Food", "French Fries"),
  "🍲": af("Food", "Pot of Food"),
  "🥐": af("Food", "Croissant"),
  "🥥": af("Food", "Coconut"),
  "🎂": af("Food", "Birthday Cake"),
  "🍪": af("Food", "Cookie"),

  // ── Faces / Emotions ──────────────────────────────────────────────────────
  "😊": af("Smilies", "Smiling Face with Smiling Eyes"),
  "😢": af("Smilies", "Crying Face"),
  "😠": af("Smilies", "Angry Face"),
  "😨": af("Smilies", "Fearful Face"),
  "😴": af("Smilies", "Sleeping Face"),
  "😳": af("Smilies", "Flushed Face"),
  "😟": af("Smilies", "Worried Face"),
  "😲": af("Smilies", "Astonished Face"),
  "🥺": af("Smilies", "Pleading Face"),
  "😌": af("Smilies", "Relieved Face"),
  "😂": af("Smilies", "Face with Tears of Joy"),
  "😤": af("Smilies", "Face with Steam from Nose"),
  "🥶": af("Smilies", "Cold Face"),
  "😬": af("Smilies", "Grimacing Face"),

  // ── Activities ────────────────────────────────────────────────────────────
  "⚽": af("Activities", "Soccer Ball"),
  "🎉": af("Activities", "Party Popper"),
  "🎨": af("Activities", "Artist Palette"),
  "🏆": af("Activities", "Trophy"),
  "🎵": af("Activities", "Musical Note"),
  "🥇": af("Activities", "1st Place Medal"),
  "🥈": af("Activities", "2nd Place Medal"),
  "🥉": af("Activities", "3rd Place Medal"),

  // ── Objects / School ──────────────────────────────────────────────────────
  "🧼": af("Objects", "Soap"),
  "🎒": af("Objects", "Backpack"),
  "✏️": af("Objects", "Pencil"),
  "📝": af("Objects", "Memo"),
  "🔬": af("Objects", "Microscope"),
  "🎓": af("Objects", "Graduation Cap"),
  "📖": af("Objects", "Open Book"),
  "🖊️": af("Objects", "Pen"),
  "🪑": af("Objects", "Chair"),
  "🚪": af("Objects", "Door"),
  "🔒": af("Objects", "Locked"),
  "📦": af("Objects", "Package"),
  "💰": af("Objects", "Money Bag"),
  "👕": af("Objects", "T-Shirt"),
  "🛠️": af("Objects", "Hammer and Wrench"),

  // ── Travel / Nature ───────────────────────────────────────────────────────
  "💧": af("Travel and places", "Droplet"),
  "🔥": af("Travel and places", "Fire"),
  "⭐": af("Travel and places", "Star"),
  "🌟": af("Travel and places", "Glowing Star"),
  "🌙": af("Travel and places", "Crescent Moon"),
  "🌗": af("Travel and places", "Last Quarter Moon"),
  "🌘": af("Travel and places", "Waning Crescent Moon"),
  "☀️": af("Travel and places", "Sun"),
  "☁️": af("Travel and places", "Cloud"),
  "🌧️": af("Travel and places", "Cloud with Rain"),
  "🌤️": af("Travel and places", "Sun Behind Small Cloud"),
  "🌳": af("Animals", "Deciduous Tree"),
  "🌲": af("Animals", "Evergreen Tree"),
  "🌸": af("Animals", "Cherry Blossom"),
  "🌾": af("Animals", "Sheaf of Rice"),
  "🌊": af("Travel and places", "Water Wave"),
  "⛰️": af("Travel and places", "Mountain"),
  "🏖️": af("Travel and places", "Beach with Umbrella"),
  "🏞️": af("Travel and places", "National Park"),

  // ── People ────────────────────────────────────────────────────────────────
  "👩": af("People", "Woman"),
  "👦": af("People", "Boy"),
  "👧": af("People", "Girl"),
  "👶": af("People", "Baby"),

  // ── Symbols ───────────────────────────────────────────────────────────────
  "❤️": af("Symbols", "Red Heart"),
  "🙏": af("Hand gestures", "Folded Hands"),
};

export function getAnimatedUrl(emoji: string): string | null {
  return ANIMATED_MAP[emoji] ?? null;
}
