// ─────────────────────────────────────────────────────────────────────────────
// Single source of truth for ALL vocabulary — lessons, quizzes, games,
// reveal cards, and progress tracking all read from this file.
// (Previously duplicated between here and VoiceSession.tsx; keep it merged.)
//
// Word ORDER is pedagogical and drives lesson batches (getWordBatch in
// VoiceSession):
//   words 0–4  → Level 1 batch
//   words 5–9  → Level 2 batch
//   words 10+  → advanced pool (Levels 3–4 draw random batches of 5)
//
// Fields:
//   sw         — Swahili word (canonical key everywhere)
//   en         — English word, short single form (shown on game tiles, used in
//                lesson prompts and transcript word-detection)
//   emoji      — artwork for games and reveal cards
//   swPhonetic — pronunciation reference; NEVER injected into the model's word
//                list (bracket notation gets read aloud) — see VoiceSession
// ─────────────────────────────────────────────────────────────────────────────

export interface QuizWord { sw: string; en: string; emoji: string; swPhonetic: string; }

export const WORD_LISTS: Record<string, QuizWord[]> = {
  animals: [
    // Level 1 — words 0–4
    { sw: "simba",      en: "lion",      emoji: "🦁", swPhonetic: "SEEM-bah"            },
    { sw: "tembo",      en: "elephant",  emoji: "🐘", swPhonetic: "TEM-bo"              },
    { sw: "twiga",      en: "giraffe",   emoji: "🦒", swPhonetic: "TWEE-gah"            },
    { sw: "mbwa",       en: "dog",       emoji: "🐕", swPhonetic: "M-bwah"              },
    { sw: "paka",       en: "cat",       emoji: "🐱", swPhonetic: "PAH-kah"             },
    // Level 2 — words 5–9
    { sw: "ndege",      en: "bird",      emoji: "🐦", swPhonetic: "n-DEH-geh"           },
    { sw: "mbuzi",      en: "goat",      emoji: "🐐", swPhonetic: "m-BOO-zee"           },
    { sw: "ng'ombe",    en: "cow",       emoji: "🐄", swPhonetic: "ng-OM-beh"           },
    { sw: "punda",      en: "donkey",    emoji: "🫏", swPhonetic: "POON-dah"            },
    { sw: "farasi",     en: "horse",     emoji: "🐎", swPhonetic: "fah-RAH-see"         },
    // Advanced pool — words 10+
    { sw: "kondoo",     en: "sheep",     emoji: "🐑", swPhonetic: "kon-DOH-oh"          },
    { sw: "kuku",       en: "chicken",   emoji: "🐔", swPhonetic: "KOO-koo"             },
    { sw: "bata",       en: "duck",      emoji: "🦆", swPhonetic: "BAH-tah"             },
    { sw: "kasuku",     en: "parrot",    emoji: "🦜", swPhonetic: "kah-SOO-koo"         },
    { sw: "nyani",      en: "monkey",    emoji: "🐒", swPhonetic: "NYAH-nee"            },
    { sw: "chui",       en: "leopard",   emoji: "🐆", swPhonetic: "CHOO-ee"             },
    { sw: "fisi",       en: "hyena",     emoji: "🐺", swPhonetic: "FEE-see"             },
    { sw: "kiboko",     en: "hippo",     emoji: "🦛", swPhonetic: "kee-BOH-koh"         },
    { sw: "sungura",    en: "rabbit",    emoji: "🐇", swPhonetic: "soon-GOO-rah"        },
    { sw: "panya",      en: "mouse",     emoji: "🐭", swPhonetic: "PAH-nyah"            },
    { sw: "nyuki",      en: "bee",       emoji: "🐝", swPhonetic: "NYOO-kee"            },
    { sw: "kipepeo",    en: "butterfly", emoji: "🦋", swPhonetic: "kee-peh-PEH-oh"      },
    { sw: "mbu",        en: "mosquito",  emoji: "🦟", swPhonetic: "M-boo"               },
    { sw: "duma",       en: "cheetah",   emoji: "🐆", swPhonetic: "DOO-mah"             },
    { sw: "faru",       en: "rhino",     emoji: "🦏", swPhonetic: "FAH-roo"             },
    { sw: "nguruwe",    en: "pig",       emoji: "🐷", swPhonetic: "ngoo-ROO-weh"        },
    { sw: "papa",       en: "shark",     emoji: "🦈", swPhonetic: "PAH-pah"             },
    { sw: "nyangumi",   en: "whale",     emoji: "🐋", swPhonetic: "nyahn-GOO-mee"       },
    { sw: "tai",        en: "eagle",     emoji: "🦅", swPhonetic: "TAH-ee"              },
    { sw: "kasa",       en: "turtle",    emoji: "🐢", swPhonetic: "KAH-sah"             },
    { sw: "ngiri",      en: "warthog",   emoji: "🐗", swPhonetic: "NGEE-ree"            },
    { sw: "pweza",      en: "octopus",   emoji: "🐙", swPhonetic: "PWEH-zah"            },
    { sw: "pundamilia", en: "zebra",     emoji: "🦓", swPhonetic: "poon-dah-mee-LEE-ah" },
    { sw: "nyati",      en: "buffalo",   emoji: "🐃", swPhonetic: "NYAH-tee"            },
    { sw: "swala",      en: "gazelle",   emoji: "🦌", swPhonetic: "SWAH-lah"            },
    { sw: "korongo",    en: "crane",     emoji: "🦢", swPhonetic: "koh-RON-goh"         },
    { sw: "kobe",       en: "tortoise",  emoji: "🐢", swPhonetic: "KOH-beh"             },
    { sw: "nge",        en: "scorpion",  emoji: "🦂", swPhonetic: "N-geh"               },
    { sw: "samaki",     en: "fish",      emoji: "🐟", swPhonetic: "sah-MAH-kee"         },
    { sw: "nyoka",      en: "snake",     emoji: "🐍", swPhonetic: "NYOH-kah"            },
  ],
  numbers: [
    // Level 1 — words 0–4
    { sw: "moja",          en: "one",         emoji: "1️⃣", swPhonetic: "MOH-jah"               },
    { sw: "mbili",         en: "two",         emoji: "2️⃣", swPhonetic: "m-BEE-lee"             },
    { sw: "tatu",          en: "three",       emoji: "3️⃣", swPhonetic: "TAH-too"               },
    { sw: "nne",           en: "four",        emoji: "4️⃣", swPhonetic: "N-neh"                 },
    { sw: "tano",          en: "five",        emoji: "5️⃣", swPhonetic: "TAH-no"                },
    // Level 2 — words 5–9
    { sw: "sita",          en: "six",         emoji: "6️⃣", swPhonetic: "SEE-tah"               },
    { sw: "saba",          en: "seven",       emoji: "7️⃣", swPhonetic: "SAH-bah"               },
    { sw: "nane",          en: "eight",       emoji: "8️⃣", swPhonetic: "NAH-neh"               },
    { sw: "tisa",          en: "nine",        emoji: "9️⃣", swPhonetic: "TEE-sah"               },
    { sw: "kumi",          en: "ten",         emoji: "🔟", swPhonetic: "KOO-mee"               },
    // Advanced pool — words 10+
    { sw: "kumi na moja",  en: "eleven",      emoji: "1️⃣1️⃣", swPhonetic: "KOO-mee nah MOH-jah"   },
    { sw: "kumi na mbili", en: "twelve",      emoji: "1️⃣2️⃣", swPhonetic: "KOO-mee nah m-BEE-lee" },
    { sw: "kumi na tatu",  en: "thirteen",    emoji: "1️⃣3️⃣", swPhonetic: "KOO-mee nah TAH-too"   },
    { sw: "kumi na nne",   en: "fourteen",    emoji: "1️⃣4️⃣", swPhonetic: "KOO-mee nah N-neh"     },
    { sw: "kumi na tano",  en: "fifteen",     emoji: "1️⃣5️⃣", swPhonetic: "KOO-mee nah TAH-no"    },
    { sw: "kumi na sita",  en: "sixteen",     emoji: "1️⃣6️⃣", swPhonetic: "KOO-mee nah SEE-tah"   },
    { sw: "kumi na saba",  en: "seventeen",   emoji: "1️⃣7️⃣", swPhonetic: "KOO-mee nah SAH-bah"   },
    { sw: "kumi na nane",  en: "eighteen",    emoji: "1️⃣8️⃣", swPhonetic: "KOO-mee nah NAH-neh"   },
    { sw: "kumi na tisa",  en: "nineteen",    emoji: "1️⃣9️⃣", swPhonetic: "KOO-mee nah TEE-sah"   },
    { sw: "ishirini",      en: "twenty",      emoji: "2️⃣0️⃣", swPhonetic: "ee-shee-REE-nee"       },
    { sw: "thelathini",    en: "thirty",      emoji: "3️⃣0️⃣", swPhonetic: "theh-lah-THEE-nee"     },
    { sw: "arobaini",      en: "forty",       emoji: "4️⃣0️⃣", swPhonetic: "ah-roh-bah-EE-nee"     },
    { sw: "hamsini",       en: "fifty",       emoji: "5️⃣0️⃣", swPhonetic: "ham-SEE-nee"           },
    { sw: "sitini",        en: "sixty",       emoji: "6️⃣0️⃣", swPhonetic: "see-TEE-nee"           },
    { sw: "sabini",        en: "seventy",     emoji: "7️⃣0️⃣", swPhonetic: "sah-BEE-nee"           },
    { sw: "themanini",     en: "eighty",      emoji: "8️⃣0️⃣", swPhonetic: "theh-mah-NEE-nee"      },
    { sw: "tisini",        en: "ninety",      emoji: "9️⃣0️⃣", swPhonetic: "tee-SEE-nee"           },
    { sw: "mia moja",      en: "one hundred", emoji: "💯", swPhonetic: "MEE-ah MOH-jah"        },
    { sw: "sifuri",        en: "zero",        emoji: "0️⃣", swPhonetic: "see-FOO-ree"           },
    { sw: "wa kwanza",     en: "first",       emoji: "🥇", swPhonetic: "wah KWAHN-zah"         },
    { sw: "wa pili",       en: "second",      emoji: "🥈", swPhonetic: "wah PEE-lee"           },
    { sw: "wa tatu",       en: "third",       emoji: "🥉", swPhonetic: "wah TAH-too"           },
    { sw: "nusu",          en: "half",        emoji: "🌓", swPhonetic: "NOO-soo"               },
    { sw: "robo",          en: "quarter",     emoji: "🍕", swPhonetic: "ROH-boh"               },
    { sw: "elfu",          en: "thousand",    emoji: "💰", swPhonetic: "EL-foo"                },
  ],
  colors: [
    // All 10 colours are used across Levels 1+2 — no advanced pool needed
    { sw: "nyekundu", en: "red",    emoji: "🔴", swPhonetic: "nyeh-KOON-doo"  },
    { sw: "bluu",     en: "blue",   emoji: "🔵", swPhonetic: "BLOO"           },
    { sw: "njano",    en: "yellow", emoji: "🟡", swPhonetic: "NJAH-no"        },
    { sw: "kijani",   en: "green",  emoji: "🟢", swPhonetic: "kee-JAH-nee"    },
    { sw: "nyeupe",   en: "white",  emoji: "⚪", swPhonetic: "nyeh-OO-peh"    },
    { sw: "nyeusi",   en: "black",  emoji: "⚫", swPhonetic: "nyeh-OO-see"    },
    { sw: "waridi",   en: "pink",   emoji: "🩷", swPhonetic: "wah-REE-dee"    },
    { sw: "zambarau", en: "purple", emoji: "🟣", swPhonetic: "zam-bah-RAH-oo" },
    { sw: "kahawia",  en: "brown",  emoji: "🟤", swPhonetic: "kah-HAH-wee-ah" },
    { sw: "kijivu",   en: "gray",   emoji: "🩶", swPhonetic: "kee-JEE-voo"    },
  ],
  body: [
    // Level 1 — words 0–4
    { sw: "kichwa",       en: "head",     emoji: "🧠", swPhonetic: "KEE-chwah"            },
    { sw: "jicho",        en: "eye",      emoji: "👁️", swPhonetic: "JEE-cho"              },
    { sw: "masikio",      en: "ears",     emoji: "👂", swPhonetic: "mah-see-KEE-oh"       },
    { sw: "pua",          en: "nose",     emoji: "👃", swPhonetic: "POO-ah"               },
    { sw: "mdomo",        en: "mouth",    emoji: "👄", swPhonetic: "m-DOH-mo"             },
    // Level 2 — words 5–9
    { sw: "mkono",        en: "hand",     emoji: "🤚", swPhonetic: "m-KOH-no"             },
    { sw: "kidole",       en: "finger",   emoji: "👆", swPhonetic: "kee-DOH-leh"          },
    { sw: "tumbo",        en: "stomach",  emoji: "🫃", swPhonetic: "TOOM-bo"              },
    { sw: "mguu",         en: "leg",      emoji: "🦵", swPhonetic: "m-GOO"                },
    { sw: "mgongo",       en: "back",     emoji: "🧍", swPhonetic: "m-GON-go"             },
    // Advanced pool — words 10+
    { sw: "uso",          en: "face",     emoji: "😊", swPhonetic: "OO-soh"               },
    { sw: "meno",         en: "teeth",    emoji: "🦷", swPhonetic: "MEH-noh"              },
    { sw: "shingo",       en: "neck",     emoji: "🦒", swPhonetic: "SHEEN-goh"            },
    { sw: "bega",         en: "shoulder", emoji: "💪", swPhonetic: "BEH-gah"              },
    { sw: "kifua",        en: "chest",    emoji: "🫀", swPhonetic: "kee-FOO-ah"           },
    { sw: "moyo",         en: "heart",    emoji: "❤️", swPhonetic: "MOH-yoh"              },
    { sw: "goti",         en: "knee",     emoji: "🦵", swPhonetic: "GOH-tee"              },
    { sw: "nywele",       en: "hair",     emoji: "💇", swPhonetic: "nyeh-WEH-leh"         },
    { sw: "ngozi",        en: "skin",     emoji: "🫴", swPhonetic: "NGO-zee"              },
    { sw: "damu",         en: "blood",    emoji: "🩸", swPhonetic: "DAH-moo"              },
    { sw: "ulimi",        en: "tongue",   emoji: "👅", swPhonetic: "oo-LEE-mee"           },
    { sw: "mfupa",        en: "bone",     emoji: "🦴", swPhonetic: "m-FOO-pah"            },
    { sw: "ubongo",       en: "brain",    emoji: "🧠", swPhonetic: "oo-BON-goh"           },
    { sw: "mapafu",       en: "lungs",    emoji: "🫁", swPhonetic: "mah-PAH-foo"          },
    { sw: "ini",          en: "liver",    emoji: "🫀", swPhonetic: "EE-nee"               },
    { sw: "figo",         en: "kidney",   emoji: "🫘", swPhonetic: "FEE-goh"              },
    { sw: "mapaja",       en: "thighs",   emoji: "🦵", swPhonetic: "mah-PAH-jah"          },
    { sw: "kiuno",        en: "waist",    emoji: "🩱", swPhonetic: "kee-OO-noh"           },
    { sw: "pumzi",        en: "breath",   emoji: "💨", swPhonetic: "POOM-zee"             },
    { sw: "jasho",        en: "sweat",    emoji: "💦", swPhonetic: "JAH-shoh"             },
    { sw: "machozi",      en: "tears",    emoji: "😢", swPhonetic: "mah-CHOH-zee"         },
    { sw: "msuli",        en: "muscle",   emoji: "💪", swPhonetic: "m-SOO-lee"            },
    { sw: "kiganja",      en: "palm",     emoji: "🖐️", swPhonetic: "kee-GAHN-jah"         },
    { sw: "taya",         en: "jaw",      emoji: "😬", swPhonetic: "TAH-yah"              },
    { sw: "shavu",        en: "cheek",    emoji: "😊", swPhonetic: "SHAH-voo"             },
    { sw: "paji",         en: "forehead", emoji: "🤦", swPhonetic: "PAH-jee"              },
    { sw: "kisigino",     en: "heel",     emoji: "🦶", swPhonetic: "kee-see-GEE-noh"      },
    { sw: "kidole gumba", en: "thumb",    emoji: "👍", swPhonetic: "kee-DOH-leh GOOM-bah" },
  ],
  people: [
    // Level 1 — words 0–4
    { sw: "mama",       en: "mother",         emoji: "👩", swPhonetic: "MAH-mah"           },
    { sw: "baba",       en: "father",         emoji: "👨", swPhonetic: "BAH-bah"           },
    { sw: "kaka",       en: "brother",        emoji: "👦", swPhonetic: "KAH-kah"           },
    { sw: "dada",       en: "sister",         emoji: "👧", swPhonetic: "DAH-dah"           },
    { sw: "bibi",       en: "grandmother",    emoji: "👵", swPhonetic: "BEE-bee"           },
    // Level 2 — words 5–9
    { sw: "babu",       en: "grandfather",    emoji: "👴", swPhonetic: "BAH-boo"           },
    { sw: "mtoto",      en: "child / baby",   emoji: "👶", swPhonetic: "m-TOH-toh"         },
    { sw: "rafiki",     en: "friend",         emoji: "🤝", swPhonetic: "rah-FEE-kee"       },
    { sw: "mjomba",     en: "uncle",          emoji: "👨‍👦", swPhonetic: "m-JOM-bah"         },
    { sw: "shangazi",   en: "aunt",           emoji: "👩‍👧", swPhonetic: "shan-GAH-zee"      },
    // Advanced pool — words 10+
    { sw: "binamu",     en: "cousin",         emoji: "👫", swPhonetic: "bee-NAH-moo"       },
    { sw: "jirani",     en: "neighbor",       emoji: "🏘️", swPhonetic: "jee-RAH-nee"       },
    { sw: "mwalimu",    en: "teacher",        emoji: "👩‍🏫", swPhonetic: "mwah-LEE-moo"      },
    { sw: "mwanafunzi", en: "student",        emoji: "🎓", swPhonetic: "mwah-nah-FOON-zee" },
    { sw: "daktari",    en: "doctor",         emoji: "👨‍⚕️", swPhonetic: "dahk-TAH-ree"      },
    { sw: "muuguzi",    en: "nurse",          emoji: "👩‍⚕️", swPhonetic: "moo-oo-GOO-zee"    },
    { sw: "kasisi",     en: "pastor",         emoji: "⛪", swPhonetic: "kah-SEE-see"       },
    { sw: "polisi",     en: "police officer", emoji: "👮", swPhonetic: "poh-LEE-see"       },
    { sw: "mkulima",    en: "farmer",         emoji: "👨‍🌾", swPhonetic: "m-koo-LEE-mah"     },
    { sw: "dereva",     en: "driver",         emoji: "🚗", swPhonetic: "deh-REH-vah"       },
  ],
  chakula: [
    // Level 1 — words 0–4
    { sw: "maji",        en: "water",      emoji: "💧", swPhonetic: "MAH-jee"             },
    { sw: "chakula",     en: "food",       emoji: "🍽️", swPhonetic: "chah-KOO-lah"        },
    { sw: "mkate",       en: "bread",      emoji: "🍞", swPhonetic: "m-KAH-teh"           },
    { sw: "matunda",     en: "fruit",      emoji: "🍎", swPhonetic: "mah-TOON-dah"        },
    { sw: "nyama",       en: "meat",       emoji: "🥩", swPhonetic: "NYAH-mah"            },
    // Level 2 — words 5–9
    { sw: "wali",        en: "rice",       emoji: "🍚", swPhonetic: "WAH-lee"             },
    { sw: "ugali",       en: "ugali",      emoji: "🫕", swPhonetic: "oo-GAH-lee"          },
    { sw: "ndizi",       en: "banana",     emoji: "🍌", swPhonetic: "n-DEE-zee"           },
    { sw: "embe",        en: "mango",      emoji: "🥭", swPhonetic: "EM-beh"              },
    { sw: "mboga",       en: "vegetables", emoji: "🥦", swPhonetic: "m-BOH-gah"           },
    // Advanced pool — words 10+
    { sw: "chai",        en: "tea",        emoji: "🫖", swPhonetic: "CHAH-ee"             },
    { sw: "maziwa",      en: "milk",       emoji: "🥛", swPhonetic: "mah-ZEE-wah"         },
    { sw: "mayai",       en: "eggs",       emoji: "🥚", swPhonetic: "mah-YAH-ee"          },
    { sw: "mahindi",     en: "maize",      emoji: "🌽", swPhonetic: "mah-HEEN-dee"        },
    { sw: "nyanya",      en: "tomato",     emoji: "🍅", swPhonetic: "NYAH-nyah"           },
    { sw: "vitunguu",    en: "onions",     emoji: "🧅", swPhonetic: "vee-toon-GOO-oo"     },
    { sw: "viazi",       en: "potatoes",   emoji: "🥔", swPhonetic: "vee-AH-zee"          },
    { sw: "maharagwe",   en: "beans",      emoji: "🫘", swPhonetic: "mah-hah-RAH-gweh"    },
    { sw: "sukari",      en: "sugar",      emoji: "🍬", swPhonetic: "soo-KAH-ree"         },
    { sw: "chumvi",      en: "salt",       emoji: "🧂", swPhonetic: "CHOOM-vee"           },
    { sw: "mafuta",      en: "oil",        emoji: "🫙", swPhonetic: "mah-FOO-tah"         },
    { sw: "asali",       en: "honey",      emoji: "🍯", swPhonetic: "ah-SAH-lee"          },
    { sw: "uji",         en: "porridge",   emoji: "🥣", swPhonetic: "OO-jee"              },
    { sw: "pilau",       en: "pilau",      emoji: "🍛", swPhonetic: "pee-LAH-oo"          },
    { sw: "keki",        en: "cake",       emoji: "🎂", swPhonetic: "KEH-kee"             },
    { sw: "biskuti",     en: "biscuits",   emoji: "🍪", swPhonetic: "bee-SKOO-tee"        },
    { sw: "pipi",        en: "sweets",     emoji: "🍬", swPhonetic: "PEE-pee"             },
    { sw: "juisi",       en: "juice",      emoji: "🧃", swPhonetic: "joo-EE-see"          },
    { sw: "soda",        en: "soda",       emoji: "🥤", swPhonetic: "SOH-dah"             },
    { sw: "nazi",        en: "coconut",    emoji: "🥥", swPhonetic: "NAH-zee"             },
    { sw: "papai",       en: "papaya",     emoji: "🍈", swPhonetic: "pah-PAH-ee"          },
    { sw: "tikiti maji", en: "watermelon", emoji: "🍉", swPhonetic: "tee-KEE-tee MAH-jee" },
    { sw: "zabibu",      en: "grapes",     emoji: "🍇", swPhonetic: "zah-BEE-boo"         },
    { sw: "karoti",      en: "carrot",     emoji: "🥕", swPhonetic: "kah-ROH-tee"         },
    { sw: "kabichi",     en: "cabbage",    emoji: "🥬", swPhonetic: "kah-BEE-chee"        },
    { sw: "chipsi",      en: "chips",      emoji: "🍟", swPhonetic: "CHEEP-see"           },
    { sw: "mchuzi",      en: "stew",       emoji: "🍲", swPhonetic: "m-CHOO-zee"          },
    { sw: "mandazi",     en: "mandazi",    emoji: "🥐", swPhonetic: "mahn-DAH-zee"        },
    { sw: "samaki",      en: "fish",       emoji: "🐟", swPhonetic: "sah-MAH-kee"         },
  ],
  vitenzi: [
    // Level 1 — words 0–4
    { sw: "kula",     en: "eat",    emoji: "🍽️", swPhonetic: "KOO-lah"           },
    { sw: "kunywa",   en: "drink",  emoji: "🥤", swPhonetic: "koo-NYWA"          },
    { sw: "kulala",   en: "sleep",  emoji: "😴", swPhonetic: "koo-LAH-lah"       },
    { sw: "kucheza",  en: "play",   emoji: "⚽", swPhonetic: "koo-CHEH-zah"      },
    { sw: "kukimbia", en: "run",    emoji: "🏃", swPhonetic: "koo-keem-BEE-ah"   },
    // Level 2 — words 5–9
    { sw: "kuruka",   en: "jump",   emoji: "🦘", swPhonetic: "koo-ROO-kah"       },
    { sw: "kusoma",   en: "read",   emoji: "📖", swPhonetic: "koo-SOH-mah"       },
    { sw: "kuimba",   en: "sing",   emoji: "🎵", swPhonetic: "koo-EEM-bah"       },
    { sw: "kupika",   en: "cook",   emoji: "🍳", swPhonetic: "koo-PEE-kah"       },
    { sw: "kutembea", en: "walk",   emoji: "🚶", swPhonetic: "koo-tem-BEH-ah"    },
    // Advanced pool — words 10+
    { sw: "kuja",     en: "come",   emoji: "🫳", swPhonetic: "KOO-jah"           },
    { sw: "kwenda",   en: "go",     emoji: "👋", swPhonetic: "KWEN-dah"          },
    { sw: "kuona",    en: "see",    emoji: "👀", swPhonetic: "koo-OH-nah"        },
    { sw: "kusikia",  en: "hear",   emoji: "👂", swPhonetic: "koo-see-KEE-ah"    },
    { sw: "kusema",   en: "speak",  emoji: "🗣️", swPhonetic: "koo-SEH-mah"       },
    { sw: "kuandika", en: "write",  emoji: "✍️", swPhonetic: "koo-ahn-DEE-kah"   },
    { sw: "kucheka",  en: "laugh",  emoji: "😂", swPhonetic: "koo-CHEH-kah"      },
    { sw: "kulia",    en: "cry",    emoji: "😢", swPhonetic: "koo-LEE-ah"        },
    { sw: "kupenda",  en: "love",   emoji: "❤️", swPhonetic: "koo-PEN-dah"       },
    { sw: "kufanya",  en: "do",     emoji: "🛠️", swPhonetic: "koo-FAH-nyah"      },
    { sw: "kutaka",   en: "want",   emoji: "🌟", swPhonetic: "koo-TAH-kah"       },
    { sw: "kujua",    en: "know",   emoji: "💡", swPhonetic: "koo-JOO-ah"        },
    { sw: "kufungua", en: "open",   emoji: "🚪", swPhonetic: "koo-foon-GOO-ah"   },
    { sw: "kufunga",  en: "close",  emoji: "🔒", swPhonetic: "koo-FOON-gah"      },
    { sw: "kusaidia", en: "help",   emoji: "🤝", swPhonetic: "koo-sah-ee-DEE-ah" },
    { sw: "kuchukua", en: "take",   emoji: "🫴", swPhonetic: "koo-choo-KOO-ah"   },
    { sw: "kuweka",   en: "put",    emoji: "📦", swPhonetic: "koo-WEH-kah"       },
    { sw: "kurudi",   en: "return", emoji: "🔄", swPhonetic: "koo-ROO-dee"       },
    { sw: "kuingia",  en: "enter",  emoji: "🏠", swPhonetic: "koo-een-GEE-ah"    },
    { sw: "kutoka",   en: "leave",  emoji: "🚶", swPhonetic: "koo-TOH-kah"       },
    { sw: "kupanda",  en: "climb",  emoji: "🧗", swPhonetic: "koo-PAHN-dah"      },
    { sw: "kuosha",   en: "wash",   emoji: "🧼", swPhonetic: "koo-OH-shah"       },
    { sw: "kuvaa",    en: "wear",   emoji: "👕", swPhonetic: "koo-VAH-ah"        },
    { sw: "kulima",   en: "farm",   emoji: "🌾", swPhonetic: "koo-LEE-mah"       },
    { sw: "kupiga",   en: "hit",    emoji: "👊", swPhonetic: "koo-PEE-gah"       },
  ],
  shule: [
    // Note: "shule" (school) is intentionally NOT first — the topic IS shule, so the
    // opening question is already about school. Teaching "shule" as Word 1 right after
    // causes the model to confuse natural conversation with formal teaching.
    // Level 1 — words 0–4
    { sw: "kitabu",    en: "book",       emoji: "📖", swPhonetic: "kee-TAH-boo"        },
    { sw: "kalamu",    en: "pen",        emoji: "🖊️", swPhonetic: "kah-LAH-moo"        },
    { sw: "darasa",    en: "classroom",  emoji: "🏫", swPhonetic: "dah-RAH-sah"        },
    { sw: "begi",      en: "bag",        emoji: "🎒", swPhonetic: "BEH-gee"            },
    { sw: "mwalimu",   en: "teacher",    emoji: "👩‍🏫", swPhonetic: "mwah-LEE-moo"       },
    // Level 2 — words 5–9
    { sw: "ubao",      en: "blackboard", emoji: "🖊️", swPhonetic: "oo-BAH-oh"          },
    { sw: "penseli",   en: "pencil",     emoji: "✏️", swPhonetic: "pen-SEH-lee"        },
    { sw: "meza",      en: "desk",       emoji: "🪑", swPhonetic: "MEH-zah"            },
    { sw: "kiti",      en: "chair",      emoji: "🪑", swPhonetic: "KEE-tee"            },
    { sw: "shule",     en: "school",     emoji: "🏫", swPhonetic: "SHOO-leh"           },
    // Advanced pool — words 10+
    { sw: "mtihani",   en: "exam",       emoji: "📝", swPhonetic: "m-tee-HAH-nee"      },
    { sw: "hesabu",    en: "maths",      emoji: "🔢", swPhonetic: "heh-SAH-boo"        },
    { sw: "sayansi",   en: "science",    emoji: "🔬", swPhonetic: "sah-YAHN-see"       },
    { sw: "sanaa",     en: "art",        emoji: "🎨", swPhonetic: "sah-NAH-ah"         },
    { sw: "historia",  en: "history",    emoji: "📜", swPhonetic: "hee-stoh-REE-ah"    },
    { sw: "jiografia", en: "geography",  emoji: "🗺️", swPhonetic: "jee-oh-grah-FEE-ah" },
    { sw: "muziki",    en: "music",      emoji: "🎵", swPhonetic: "moo-ZEE-kee"        },
    { sw: "lugha",     en: "language",   emoji: "🗣️", swPhonetic: "LOO-ghah"           },
    { sw: "mchezo",    en: "sport",      emoji: "⚽", swPhonetic: "m-CHEH-zo"          },
    { sw: "lepe",      en: "eraser",     emoji: "🧹", swPhonetic: "LEH-peh"            },
    { sw: "rula",      en: "ruler",      emoji: "📏", swPhonetic: "ROO-lah"            },
    { sw: "chaki",     en: "chalk",      emoji: "🖍️", swPhonetic: "CHAH-kee"           },
    { sw: "sare",      en: "uniform",    emoji: "👔", swPhonetic: "SAH-reh"            },
    { sw: "ratiba",    en: "timetable",  emoji: "📅", swPhonetic: "rah-TEE-bah"        },
    { sw: "likizo",    en: "holiday",    emoji: "🏖️", swPhonetic: "lee-KEE-zo"         },
    { sw: "somo",      en: "lesson",     emoji: "📖", swPhonetic: "SOH-moh"            },
    { sw: "dirisha",   en: "window",     emoji: "🪟", swPhonetic: "dee-REE-shah"       },
    { sw: "ramani",    en: "map",        emoji: "🗺️", swPhonetic: "rah-MAH-nee"        },
    { sw: "picha",     en: "picture",    emoji: "📷", swPhonetic: "PEE-chah"           },
    { sw: "tuzo",      en: "prize",      emoji: "🏆", swPhonetic: "TOO-zo"             },
    { sw: "masomo",    en: "studies",    emoji: "📚", swPhonetic: "mah-SOH-moh"        },
    { sw: "elimu",     en: "education",  emoji: "🎓", swPhonetic: "eh-LEE-moo"         },
  ],
  hisia: [
    // Level 1 — words 0–4
    { sw: "furaha",    en: "happiness",     emoji: "😊", swPhonetic: "foo-RAH-hah"        },
    { sw: "huzuni",    en: "sadness",       emoji: "😢", swPhonetic: "hoo-ZOO-nee"        },
    { sw: "hasira",    en: "anger",         emoji: "😠", swPhonetic: "hah-SEE-rah"        },
    { sw: "hofu",      en: "fear",          emoji: "😨", swPhonetic: "HOH-foo"            },
    { sw: "upendo",    en: "love",          emoji: "❤️", swPhonetic: "oo-PEN-doh"         },
    // Level 2 — words 5–9
    { sw: "uchovu",    en: "tiredness",     emoji: "😴", swPhonetic: "oo-CHOH-voo"        },
    { sw: "shangwe",   en: "excitement",    emoji: "🎉", swPhonetic: "SHAN-gweh"          },
    { sw: "aibu",      en: "shame",         emoji: "😳", swPhonetic: "ah-EE-boo"          },
    { sw: "fahari",    en: "pride",         emoji: "😤", swPhonetic: "fah-HAH-ree"        },
    { sw: "wasiwasi",  en: "worry",         emoji: "😟", swPhonetic: "wah-see-WAH-see"    },
    // Advanced pool — words 10+
    { sw: "mshangao",  en: "surprise",      emoji: "😲", swPhonetic: "m-shah-NGA-oh"      },
    { sw: "ujasiri",   en: "courage",       emoji: "💪", swPhonetic: "oo-jah-SEE-ree"     },
    { sw: "huruma",    en: "compassion",    emoji: "🥺", swPhonetic: "hoo-ROO-mah"        },
    { sw: "wivu",      en: "jealousy",      emoji: "😒", swPhonetic: "WEE-voo"            },
    { sw: "upole",     en: "gentleness",    emoji: "🕊️", swPhonetic: "oo-POH-leh"         },
    { sw: "heshima",   en: "respect",       emoji: "🙏", swPhonetic: "heh-SHEE-mah"       },
    { sw: "shukrani",  en: "gratitude",     emoji: "🙏", swPhonetic: "shoo-KRAH-nee"      },
    { sw: "matumaini", en: "hope",          emoji: "🌟", swPhonetic: "mah-too-mah-EE-nee" },
    { sw: "amani",     en: "peace",         emoji: "🕊️", swPhonetic: "ah-MAH-nee"         },
    { sw: "imani",     en: "faith",         emoji: "🙏", swPhonetic: "ee-MAH-nee"         },
    { sw: "subira",    en: "patience",      emoji: "⏳", swPhonetic: "soo-BEE-rah"        },
    { sw: "shauku",    en: "enthusiasm",    emoji: "🌟", swPhonetic: "shah-OO-koo"        },
    { sw: "tamaa",     en: "desire",        emoji: "🌠", swPhonetic: "tah-MAH-ah"         },
    { sw: "starehe",   en: "relaxation",    emoji: "😌", swPhonetic: "stah-REH-heh"       },
    { sw: "burudani",  en: "entertainment", emoji: "🎭", swPhonetic: "boo-roo-DAH-nee"    },
    { sw: "roho",      en: "soul",          emoji: "💫", swPhonetic: "ROH-hoh"            },
    { sw: "pendo",     en: "affection",     emoji: "💕", swPhonetic: "PEN-doh"            },
    { sw: "hamu",      en: "longing",       emoji: "💭", swPhonetic: "HAH-moo"            },
    { sw: "kiburi",    en: "arrogance",     emoji: "😤", swPhonetic: "kee-BOO-ree"        },
    { sw: "utulivu",   en: "calmness",      emoji: "😌", swPhonetic: "oo-too-LEE-voo"     },
  ],
  mazingira: [
    // Level 1 — words 0–4
    { sw: "mti",        en: "tree",      emoji: "🌳", swPhonetic: "M-tee"               },
    { sw: "jua",        en: "sun",       emoji: "☀️", swPhonetic: "JOO-ah"              },
    { sw: "mvua",       en: "rain",      emoji: "🌧️", swPhonetic: "M-voo-ah"            },
    { sw: "ardhi",      en: "ground",    emoji: "🌍", swPhonetic: "AR-dee"              },
    { sw: "maua",       en: "flowers",   emoji: "🌸", swPhonetic: "mah-OO-ah"           },
    // Level 2 — words 5–9
    { sw: "mto",        en: "river",     emoji: "🏞️", swPhonetic: "M-toh"               },
    { sw: "mlima",      en: "mountain",  emoji: "⛰️", swPhonetic: "m-LEE-mah"           },
    { sw: "bahari",     en: "ocean",     emoji: "🌊", swPhonetic: "bah-HAH-ree"         },
    { sw: "shamba",     en: "farm",      emoji: "🌾", swPhonetic: "SHAM-bah"            },
    { sw: "msitu",      en: "forest",    emoji: "🌲", swPhonetic: "m-SEE-too"           },
    // Advanced pool — words 10+
    { sw: "nyika",      en: "savanna",   emoji: "🌾", swPhonetic: "NYEE-kah"            },
    { sw: "mchanga",    en: "sand",      emoji: "🏖️", swPhonetic: "m-CHAHN-gah"         },
    { sw: "jiwe",       en: "stone",     emoji: "🪨", swPhonetic: "JEE-weh"             },
    { sw: "udongo",     en: "soil",      emoji: "🌍", swPhonetic: "oo-DON-goh"          },
    { sw: "upepo",      en: "wind",      emoji: "💨", swPhonetic: "oo-PEH-poh"          },
    { sw: "baridi",     en: "cold",      emoji: "🥶", swPhonetic: "bah-REE-dee"         },
    { sw: "joto",       en: "heat",      emoji: "🔥", swPhonetic: "JOH-toh"             },
    { sw: "anga",       en: "sky",       emoji: "🌤️", swPhonetic: "AHN-gah"             },
    { sw: "nyota",      en: "star",      emoji: "⭐", swPhonetic: "NYOH-tah"            },
    { sw: "mwezi",      en: "moon",      emoji: "🌙", swPhonetic: "MWEH-zee"            },
    { sw: "wingu",      en: "cloud",     emoji: "☁️", swPhonetic: "WEEN-goo"            },
    { sw: "ngurumo",    en: "thunder",   emoji: "⛈️", swPhonetic: "ngoo-ROO-moh"        },
    { sw: "radi",       en: "lightning", emoji: "⚡", swPhonetic: "RAH-dee"             },
    { sw: "mwanga",     en: "light",     emoji: "💡", swPhonetic: "MWAHN-gah"           },
    { sw: "giza",       en: "darkness",  emoji: "🌑", swPhonetic: "GEE-zah"             },
    { sw: "moto",       en: "fire",      emoji: "🔥", swPhonetic: "MOH-toh"             },
    { sw: "moshi",      en: "smoke",     emoji: "💨", swPhonetic: "MOH-shee"            },
    { sw: "maporomoko", en: "waterfall", emoji: "🌊", swPhonetic: "mah-poh-roh-MOH-koh" },
    { sw: "ziwa",       en: "lake",      emoji: "🏞️", swPhonetic: "ZEE-wah"             },
    { sw: "kisiwa",     en: "island",    emoji: "🏝️", swPhonetic: "kee-SEE-wah"         },
    { sw: "jangwa",     en: "desert",    emoji: "🏜️", swPhonetic: "JAHN-gwah"           },
    { sw: "bonde",      en: "valley",    emoji: "⛰️", swPhonetic: "BON-deh"             },
    { sw: "pwani",      en: "beach",     emoji: "🏖️", swPhonetic: "PWAH-nee"            },
    { sw: "barafu",     en: "ice",       emoji: "🧊", swPhonetic: "bah-RAH-foo"         },
  ],
};
