export interface QuizWord { sw: string; en: string; emoji: string; }

export const WORD_LISTS: Record<string, QuizWord[]> = {
  animals: [
    { sw: "simba",      en: "lion",      emoji: "🦁" },
    { sw: "tembo",      en: "elephant",  emoji: "🐘" },
    { sw: "twiga",      en: "giraffe",   emoji: "🦒" },
    { sw: "mbwa",       en: "dog",       emoji: "🐕" },
    { sw: "paka",       en: "cat",       emoji: "🐱" },
    { sw: "ndege",      en: "bird",      emoji: "🐦" },
    { sw: "mbuzi",      en: "goat",      emoji: "🐐" },
    { sw: "ng'ombe",    en: "cow",       emoji: "🐄" },
    { sw: "punda",      en: "donkey",    emoji: "🫏" },
    { sw: "farasi",     en: "horse",     emoji: "🐎" },
    { sw: "kondoo",     en: "sheep",     emoji: "🐑" },
    { sw: "kuku",       en: "chicken",   emoji: "🐔" },
    { sw: "bata",       en: "duck",      emoji: "🦆" },
    { sw: "kasuku",     en: "parrot",    emoji: "🦜" },
    { sw: "nyani",      en: "monkey",    emoji: "🐒" },
    { sw: "chui",       en: "leopard",   emoji: "🐆" },
    { sw: "fisi",       en: "hyena",     emoji: "🐺" },
    { sw: "kiboko",     en: "hippo",     emoji: "🦛" },
    { sw: "sungura",    en: "rabbit",    emoji: "🐇" },
    { sw: "panya",      en: "mouse",     emoji: "🐭" },
    { sw: "duma",       en: "cheetah",   emoji: "🐆" },
    { sw: "faru",       en: "rhino",     emoji: "🦏" },
    { sw: "pundamilia", en: "zebra",     emoji: "🦓" },
    { sw: "nyati",      en: "buffalo",   emoji: "🐃" },
    { sw: "tai",        en: "eagle",     emoji: "🦅" },
    { sw: "nyoka",      en: "snake",     emoji: "🐍" },
    { sw: "nyuki",      en: "bee",       emoji: "🐝" },
    { sw: "kipepeo",    en: "butterfly", emoji: "🦋" },
    { sw: "mbu",        en: "mosquito",  emoji: "🦟" },
    { sw: "nguruwe",    en: "pig",       emoji: "🐷" },
    { sw: "papa",       en: "shark",     emoji: "🦈" },
    { sw: "nyangumi",   en: "whale",     emoji: "🐋" },
    { sw: "kasa",       en: "turtle",    emoji: "🐢" },
    { sw: "ngiri",      en: "warthog",   emoji: "🐗" },
    { sw: "pweza",      en: "octopus",   emoji: "🐙" },
    { sw: "swala",      en: "gazelle",   emoji: "🦌" },
    { sw: "korongo",    en: "crane",     emoji: "🦢" },
    { sw: "kobe",       en: "tortoise",  emoji: "🐢" },
    { sw: "nge",        en: "scorpion",  emoji: "🦂" },
    { sw: "samaki",     en: "fish",      emoji: "🐟" },
  ],
  numbers: [
    { sw: "moja",          en: "one",      emoji: "1️⃣" },
    { sw: "mbili",         en: "two",      emoji: "2️⃣" },
    { sw: "tatu",          en: "three",    emoji: "3️⃣" },
    { sw: "nne",           en: "four",     emoji: "4️⃣" },
    { sw: "tano",          en: "five",     emoji: "5️⃣" },
    { sw: "sita",          en: "six",      emoji: "6️⃣" },
    { sw: "saba",          en: "seven",    emoji: "7️⃣" },
    { sw: "nane",          en: "eight",    emoji: "8️⃣" },
    { sw: "tisa",          en: "nine",     emoji: "9️⃣" },
    { sw: "kumi",          en: "ten",      emoji: "🔟" },
    { sw: "kumi na moja",  en: "eleven",   emoji: "1️⃣1️⃣" },
    { sw: "kumi na mbili", en: "twelve",   emoji: "1️⃣2️⃣" },
    { sw: "kumi na tatu",  en: "thirteen", emoji: "1️⃣3️⃣" },
    { sw: "ishirini",      en: "twenty",   emoji: "2️⃣0️⃣" },
    { sw: "thelathini",    en: "thirty",   emoji: "3️⃣0️⃣" },
    { sw: "hamsini",       en: "fifty",    emoji: "5️⃣0️⃣" },
    { sw: "mia moja",      en: "hundred",  emoji: "💯" },
    { sw: "sifuri",        en: "zero",      emoji: "0️⃣" },
    { sw: "kumi na nne",  en: "fourteen",  emoji: "1️⃣4️⃣" },
    { sw: "kumi na tano", en: "fifteen",   emoji: "1️⃣5️⃣" },
    { sw: "kumi na sita", en: "sixteen",   emoji: "1️⃣6️⃣" },
    { sw: "kumi na saba", en: "seventeen", emoji: "1️⃣7️⃣" },
    { sw: "kumi na nane", en: "eighteen",  emoji: "1️⃣8️⃣" },
    { sw: "kumi na tisa", en: "nineteen",  emoji: "1️⃣9️⃣" },
    { sw: "arobaini",     en: "forty",     emoji: "4️⃣0️⃣" },
    { sw: "sitini",       en: "sixty",     emoji: "6️⃣0️⃣" },
    { sw: "sabini",       en: "seventy",   emoji: "7️⃣0️⃣" },
    { sw: "themanini",    en: "eighty",    emoji: "8️⃣0️⃣" },
    { sw: "tisini",       en: "ninety",    emoji: "9️⃣0️⃣" },
    { sw: "wa kwanza",    en: "first",     emoji: "🥇" },
    { sw: "wa pili",      en: "second",    emoji: "🥈" },
    { sw: "wa tatu",      en: "third",     emoji: "🥉" },
    { sw: "nusu",         en: "half",      emoji: "🌗" },
    { sw: "robo",         en: "quarter",   emoji: "🌘" },
    { sw: "elfu",         en: "thousand",  emoji: "💰" },
  ],
  colors: [
    { sw: "nyekundu", en: "red",    emoji: "🔴" },
    { sw: "bluu",     en: "blue",   emoji: "🔵" },
    { sw: "njano",    en: "yellow", emoji: "🟡" },
    { sw: "kijani",   en: "green",  emoji: "🟢" },
    { sw: "nyeupe",   en: "white",  emoji: "⚪" },
    { sw: "nyeusi",   en: "black",  emoji: "⚫" },
    { sw: "waridi",   en: "pink",   emoji: "🩷" },
    { sw: "zambarau", en: "purple", emoji: "🟣" },
    { sw: "kahawia",  en: "brown",  emoji: "🟤" },
    { sw: "kijivu",   en: "gray",   emoji: "🩶" },
  ],
  body: [
    { sw: "kichwa",  en: "head",     emoji: "🧠" },
    { sw: "jicho",   en: "eye",      emoji: "👁️" },
    { sw: "masikio", en: "ears",     emoji: "👂" },
    { sw: "pua",     en: "nose",     emoji: "👃" },
    { sw: "mdomo",   en: "mouth",    emoji: "👄" },
    { sw: "mkono",   en: "hand",     emoji: "🤚" },
    { sw: "kidole",  en: "finger",   emoji: "👆" },
    { sw: "tumbo",   en: "stomach",  emoji: "🫃" },
    { sw: "mguu",    en: "leg",      emoji: "🦵" },
    { sw: "mgongo",  en: "back",     emoji: "🧍" },
    { sw: "uso",     en: "face",     emoji: "😊" },
    { sw: "meno",    en: "teeth",    emoji: "🦷" },
    { sw: "shingo",  en: "neck",     emoji: "🦒" },
    { sw: "bega",    en: "shoulder", emoji: "💪" },
    { sw: "kifua",   en: "chest",    emoji: "🫀" },
    { sw: "moyo",    en: "heart",    emoji: "❤️" },
    { sw: "goti",    en: "knee",     emoji: "🦵" },
    { sw: "nywele",  en: "hair",     emoji: "💇" },
    { sw: "ngozi",   en: "skin",     emoji: "🫴" },
    { sw: "damu",         en: "blood",    emoji: "🩸" },
    { sw: "ulimi",        en: "tongue",   emoji: "👅" },
    { sw: "mfupa",        en: "bone",     emoji: "🦴" },
    { sw: "ubongo",       en: "brain",    emoji: "🧠" },
    { sw: "mapafu",       en: "lungs",    emoji: "🫁" },
    { sw: "ini",          en: "liver",    emoji: "🫀" },
    { sw: "figo",         en: "kidney",   emoji: "🫘" },
    { sw: "mapaja",       en: "thighs",   emoji: "🦵" },
    { sw: "kiuno",        en: "waist",    emoji: "🩱" },
    { sw: "pumzi",        en: "breath",   emoji: "💨" },
    { sw: "jasho",        en: "sweat",    emoji: "💦" },
    { sw: "machozi",      en: "tears",    emoji: "😢" },
    { sw: "msuli",        en: "muscle",   emoji: "💪" },
    { sw: "kiganja",      en: "palm",     emoji: "🖐️" },
    { sw: "taya",         en: "jaw",      emoji: "😬" },
    { sw: "shavu",        en: "cheek",    emoji: "😊" },
    { sw: "paji",         en: "forehead", emoji: "🤦" },
    { sw: "kisigino",     en: "heel",     emoji: "🦶" },
    { sw: "kidole gumba", en: "thumb",    emoji: "👍" },
  ],
  people: [
    { sw: "mama",       en: "mother",        emoji: "👩" },
    { sw: "baba",       en: "father",        emoji: "👨" },
    { sw: "kaka",       en: "brother",       emoji: "👦" },
    { sw: "dada",       en: "sister",        emoji: "👧" },
    { sw: "bibi",       en: "grandmother",   emoji: "👵" },
    { sw: "babu",       en: "grandfather",   emoji: "👴" },
    { sw: "mtoto",      en: "child / baby",  emoji: "👶" },
    { sw: "rafiki",     en: "friend",        emoji: "🤝" },
    { sw: "mjomba",     en: "uncle",         emoji: "👨‍👦" },
    { sw: "shangazi",   en: "aunt",          emoji: "👩‍👧" },
    { sw: "binamu",     en: "cousin",        emoji: "👫" },
    { sw: "jirani",     en: "neighbor",      emoji: "🏘️" },
    { sw: "mwalimu",    en: "teacher",       emoji: "👩‍🏫" },
    { sw: "mwanafunzi", en: "student",       emoji: "🎓" },
    { sw: "daktari",    en: "doctor",        emoji: "👨‍⚕️" },
    { sw: "muuguzi",    en: "nurse",         emoji: "👩‍⚕️" },
    { sw: "polisi",     en: "police officer",emoji: "👮" },
    { sw: "mkulima",    en: "farmer",         emoji: "👨‍🌾" },
    { sw: "dereva",     en: "driver",         emoji: "🚗" },
    { sw: "kasisi",     en: "pastor",         emoji: "⛪" },
  ],
  chakula: [
    { sw: "maji",      en: "water",      emoji: "💧" },
    { sw: "chakula",   en: "food",       emoji: "🍽️" },
    { sw: "mkate",     en: "bread",      emoji: "🍞" },
    { sw: "matunda",   en: "fruit",      emoji: "🍎" },
    { sw: "nyama",     en: "meat",       emoji: "🥩" },
    { sw: "wali",      en: "rice",       emoji: "🍚" },
    { sw: "ugali",     en: "ugali",      emoji: "🫕" },
    { sw: "ndizi",     en: "banana",     emoji: "🍌" },
    { sw: "embe",      en: "mango",      emoji: "🥭" },
    { sw: "mboga",     en: "vegetables", emoji: "🥦" },
    { sw: "chai",      en: "tea",        emoji: "🫖" },
    { sw: "maziwa",    en: "milk",       emoji: "🥛" },
    { sw: "mayai",     en: "eggs",       emoji: "🥚" },
    { sw: "mahindi",   en: "maize",      emoji: "🌽" },
    { sw: "nyanya",    en: "tomato",     emoji: "🍅" },
    { sw: "maharagwe", en: "beans",      emoji: "🫘" },
    { sw: "sukari",    en: "sugar",      emoji: "🍬" },
    { sw: "asali",      en: "honey",       emoji: "🍯" },
    { sw: "uji",        en: "porridge",    emoji: "🥣" },
    { sw: "samaki",     en: "fish",        emoji: "🐟" },
    { sw: "vitunguu",   en: "onions",      emoji: "🧅" },
    { sw: "viazi",      en: "potatoes",    emoji: "🥔" },
    { sw: "chumvi",     en: "salt",        emoji: "🧂" },
    { sw: "mafuta",     en: "oil",         emoji: "🫙" },
    { sw: "pilau",      en: "pilau",       emoji: "🍛" },
    { sw: "keki",       en: "cake",        emoji: "🎂" },
    { sw: "biskuti",    en: "biscuits",    emoji: "🍪" },
    { sw: "pipi",       en: "sweets",      emoji: "🍬" },
    { sw: "juisi",      en: "juice",       emoji: "🧃" },
    { sw: "soda",       en: "soda",        emoji: "🥤" },
    { sw: "nazi",       en: "coconut",     emoji: "🥥" },
    { sw: "papai",      en: "papaya",      emoji: "🍈" },
    { sw: "tikiti maji",en: "watermelon",  emoji: "🍉" },
    { sw: "zabibu",     en: "grapes",      emoji: "🍇" },
    { sw: "karoti",     en: "carrot",      emoji: "🥕" },
    { sw: "kabichi",    en: "cabbage",     emoji: "🥬" },
    { sw: "chipsi",     en: "chips",       emoji: "🍟" },
    { sw: "mchuzi",     en: "stew",        emoji: "🍲" },
    { sw: "mandazi",    en: "mandazi",     emoji: "🥐" },
  ],
  vitenzi: [
    { sw: "kula",     en: "eat",   emoji: "🍽️" },
    { sw: "kunywa",   en: "drink", emoji: "🥤" },
    { sw: "kulala",   en: "sleep", emoji: "😴" },
    { sw: "kucheza",  en: "play",  emoji: "⚽" },
    { sw: "kukimbia", en: "run",   emoji: "🏃" },
    { sw: "kuruka",   en: "jump",  emoji: "🦘" },
    { sw: "kusoma",   en: "read",  emoji: "📖" },
    { sw: "kuimba",   en: "sing",  emoji: "🎵" },
    { sw: "kupika",   en: "cook",  emoji: "🍳" },
    { sw: "kutembea", en: "walk",  emoji: "🚶" },
    { sw: "kuja",     en: "come",  emoji: "🫳" },
    { sw: "kwenda",   en: "go",    emoji: "👋" },
    { sw: "kuona",    en: "see",   emoji: "👀" },
    { sw: "kusikia",  en: "hear",  emoji: "👂" },
    { sw: "kusema",   en: "speak", emoji: "🗣️" },
    { sw: "kuandika", en: "write", emoji: "✍️" },
    { sw: "kucheka",  en: "laugh", emoji: "😂" },
    { sw: "kupenda",  en: "love",  emoji: "❤️" },
    { sw: "kusaidia", en: "help",  emoji: "🤝" },
    { sw: "kuosha",   en: "wash",   emoji: "🧼" },
    { sw: "kulia",    en: "cry",    emoji: "😢" },
    { sw: "kufanya",  en: "do",     emoji: "🛠️" },
    { sw: "kutaka",   en: "want",   emoji: "🌟" },
    { sw: "kujua",    en: "know",   emoji: "💡" },
    { sw: "kufungua", en: "open",   emoji: "🚪" },
    { sw: "kufunga",  en: "close",  emoji: "🔒" },
    { sw: "kuchukua", en: "take",   emoji: "🫴" },
    { sw: "kuweka",   en: "put",    emoji: "📦" },
    { sw: "kurudi",   en: "return", emoji: "🔄" },
    { sw: "kuingia",  en: "enter",  emoji: "🏠" },
    { sw: "kutoka",   en: "leave",  emoji: "🚶" },
    { sw: "kupanda",  en: "climb",  emoji: "🧗" },
    { sw: "kuvaa",    en: "wear",   emoji: "👕" },
    { sw: "kulima",   en: "farm",   emoji: "🌾" },
    { sw: "kupiga",   en: "hit",    emoji: "👊" },
  ],
  shule: [
    { sw: "shule",    en: "school",     emoji: "🏫" },
    { sw: "kitabu",   en: "book",       emoji: "📖" },
    { sw: "kalamu",   en: "pen",        emoji: "🖊️" },
    { sw: "darasa",   en: "classroom",  emoji: "🏫" },
    { sw: "begi",     en: "bag",        emoji: "🎒" },
    { sw: "ubao",     en: "blackboard", emoji: "🖊️" },
    { sw: "penseli",  en: "pencil",     emoji: "✏️" },
    { sw: "meza",     en: "desk",       emoji: "🪑" },
    { sw: "kiti",     en: "chair",      emoji: "🪑" },
    { sw: "mwalimu",  en: "teacher",    emoji: "👩‍🏫" },
    { sw: "mtihani",  en: "exam",       emoji: "📝" },
    { sw: "hesabu",   en: "maths",      emoji: "🔢" },
    { sw: "sayansi",  en: "science",    emoji: "🔬" },
    { sw: "sanaa",    en: "art",        emoji: "🎨" },
    { sw: "muziki",   en: "music",      emoji: "🎵" },
    { sw: "lugha",    en: "language",   emoji: "🗣️" },
    { sw: "likizo",   en: "holiday",    emoji: "🏖️" },
    { sw: "somo",     en: "lesson",     emoji: "📖" },
    { sw: "tuzo",     en: "prize",       emoji: "🏆" },
    { sw: "elimu",    en: "education",  emoji: "🎓" },
    { sw: "historia", en: "history",    emoji: "📜" },
    { sw: "jiografia",en: "geography",  emoji: "🗺️" },
    { sw: "mchezo",   en: "sport",      emoji: "⚽" },
    { sw: "lepe",     en: "eraser",     emoji: "🧹" },
    { sw: "rula",     en: "ruler",      emoji: "📏" },
    { sw: "chaki",    en: "chalk",      emoji: "🖍️" },
    { sw: "sare",     en: "uniform",    emoji: "👔" },
    { sw: "ratiba",   en: "timetable",  emoji: "📅" },
    { sw: "dirisha",  en: "window",     emoji: "🪟" },
    { sw: "ramani",   en: "map",        emoji: "🗺️" },
    { sw: "picha",    en: "picture",    emoji: "📷" },
    { sw: "masomo",   en: "studies",    emoji: "📚" },
  ],
  hisia: [
    { sw: "furaha",    en: "happiness",  emoji: "😊" },
    { sw: "huzuni",    en: "sadness",    emoji: "😢" },
    { sw: "hasira",    en: "anger",      emoji: "😠" },
    { sw: "hofu",      en: "fear",       emoji: "😨" },
    { sw: "upendo",    en: "love",       emoji: "❤️" },
    { sw: "uchovu",    en: "tiredness",  emoji: "😴" },
    { sw: "shangwe",   en: "excitement", emoji: "🎉" },
    { sw: "aibu",      en: "shame",      emoji: "😳" },
    { sw: "fahari",    en: "pride",      emoji: "😤" },
    { sw: "wasiwasi",  en: "worry",      emoji: "😟" },
    { sw: "mshangao",  en: "surprise",   emoji: "😲" },
    { sw: "ujasiri",   en: "courage",    emoji: "💪" },
    { sw: "huruma",    en: "compassion", emoji: "🥺" },
    { sw: "heshima",   en: "respect",    emoji: "🙏" },
    { sw: "shukrani",  en: "gratitude",  emoji: "🙏" },
    { sw: "matumaini", en: "hope",       emoji: "🌟" },
    { sw: "amani",     en: "peace",      emoji: "🕊️" },
    { sw: "subira",    en: "patience",   emoji: "⏳" },
    { sw: "shauku",    en: "enthusiasm", emoji: "🌟" },
    { sw: "utulivu",   en: "calmness",   emoji: "😌" },
    { sw: "wivu",      en: "jealousy",   emoji: "😒" },
    { sw: "upole",     en: "gentleness", emoji: "🕊️" },
    { sw: "imani",     en: "faith",      emoji: "🙏" },
    { sw: "tamaa",     en: "desire",     emoji: "🌠" },
    { sw: "starehe",   en: "relaxation", emoji: "😌" },
    { sw: "burudani",  en: "entertainment", emoji: "🎭" },
    { sw: "roho",      en: "soul",       emoji: "💫" },
    { sw: "pendo",     en: "affection",  emoji: "💕" },
    { sw: "hamu",      en: "longing",    emoji: "💭" },
    { sw: "kiburi",    en: "arrogance",  emoji: "😤" },
  ],
  mazingira: [
    { sw: "mti",    en: "tree",     emoji: "🌳" },
    { sw: "jua",    en: "sun",      emoji: "☀️" },
    { sw: "mvua",   en: "rain",     emoji: "🌧️" },
    { sw: "ardhi",  en: "ground",   emoji: "🌍" },
    { sw: "maua",   en: "flowers",  emoji: "🌸" },
    { sw: "mto",    en: "river",    emoji: "🏞️" },
    { sw: "mlima",  en: "mountain", emoji: "⛰️" },
    { sw: "bahari", en: "ocean",    emoji: "🌊" },
    { sw: "shamba", en: "farm",     emoji: "🌾" },
    { sw: "msitu",  en: "forest",   emoji: "🌲" },
    { sw: "upepo",  en: "wind",     emoji: "💨" },
    { sw: "baridi", en: "cold",     emoji: "🥶" },
    { sw: "joto",   en: "heat",     emoji: "🔥" },
    { sw: "anga",   en: "sky",      emoji: "🌤️" },
    { sw: "nyota",  en: "star",     emoji: "⭐" },
    { sw: "mwezi",  en: "moon",     emoji: "🌙" },
    { sw: "wingu",  en: "cloud",    emoji: "☁️" },
    { sw: "moto",   en: "fire",     emoji: "🔥" },
    { sw: "ziwa",        en: "lake",      emoji: "🏞️" },
    { sw: "pwani",       en: "beach",     emoji: "🏖️" },
    { sw: "nyika",       en: "savanna",   emoji: "🌾" },
    { sw: "mchanga",     en: "sand",      emoji: "🏖️" },
    { sw: "jiwe",        en: "stone",     emoji: "🪨" },
    { sw: "udongo",      en: "soil",      emoji: "🌍" },
    { sw: "ngurumo",     en: "thunder",   emoji: "⛈️" },
    { sw: "radi",        en: "lightning", emoji: "⚡" },
    { sw: "mwanga",      en: "light",     emoji: "💡" },
    { sw: "giza",        en: "darkness",  emoji: "🌑" },
    { sw: "moshi",       en: "smoke",     emoji: "💨" },
    { sw: "maporomoko",  en: "waterfall", emoji: "🌊" },
    { sw: "kisiwa",      en: "island",    emoji: "🏝️" },
    { sw: "jangwa",      en: "desert",    emoji: "🏜️" },
    { sw: "bonde",       en: "valley",    emoji: "⛰️" },
    { sw: "barafu",      en: "ice",       emoji: "🧊" },
  ],
};
